name: swarnim-eks 
version: "1.29"
# roleArn: arn:aws:iam::123456789012:role/my-cluster-role if not provided, pulumi will create a new role
publicAccessCidrs:
  - 0.0.0.0/0
serviceIpv4Cidr: 172.20.0.0/16
securityGroupIds:
  - sg-06bfd6162258d07f7
subnetIds:
  - subnet-027691384e95e1c10
  - subnet-0bad1990bdb6919ec
tags:
  pod: sre